version: '3.7'
services:
  profiles:
    image: mitra-integrasi
    build:
      context: .
      dockerfile: api.Dockerfile
    #volumes:
    #  - ./:/my-service-name
    ports:
      - 4181:80
    environment:
      - APP_VER=1.0.0
      - APP_NAME=mitra-integrasi
      - APP_PORT=80
      - COCKCROACH_DB_CONN_STR=/run/secrets/cockroach_conn_str
    secrets:
      - cockroach_conn_str

secrets:
  secret-phrase:
    external: true
  secret-in-a-file:
    external: true
  cockroach_conn_str:
    file: ./cockroach_conn_str.txt