// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.12.3
// source: riwayatgolonganpesertabkn_service.proto

package v1

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type RiwayatGolonganPesertaRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Nip string `protobuf:"bytes,1,opt,name=nip,proto3" json:"nip,omitempty"`
}

func (x *RiwayatGolonganPesertaRequest) Reset() {
	*x = RiwayatGolonganPesertaRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_riwayatgolonganpesertabkn_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RiwayatGolonganPesertaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RiwayatGolonganPesertaRequest) ProtoMessage() {}

func (x *RiwayatGolonganPesertaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_riwayatgolonganpesertabkn_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RiwayatGolonganPesertaRequest.ProtoReflect.Descriptor instead.
func (*RiwayatGolonganPesertaRequest) Descriptor() ([]byte, []int) {
	return file_riwayatgolonganpesertabkn_service_proto_rawDescGZIP(), []int{0}
}

func (x *RiwayatGolonganPesertaRequest) GetNip() string {
	if x != nil {
		return x.Nip
	}
	return ""
}

type RiwayatGolonganPesertaResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status             string                        `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	MessageCode        string                        `protobuf:"bytes,2,opt,name=message_code,json=messageCode,proto3" json:"message_code,omitempty"`
	MessageDescription string                        `protobuf:"bytes,3,opt,name=message_description,json=messageDescription,proto3" json:"message_description,omitempty"`
	Data               []*RiwayatGolonganPesertaData `protobuf:"bytes,4,rep,name=data,proto3" json:"data,omitempty"`
}

func (x *RiwayatGolonganPesertaResponse) Reset() {
	*x = RiwayatGolonganPesertaResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_riwayatgolonganpesertabkn_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RiwayatGolonganPesertaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RiwayatGolonganPesertaResponse) ProtoMessage() {}

func (x *RiwayatGolonganPesertaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_riwayatgolonganpesertabkn_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RiwayatGolonganPesertaResponse.ProtoReflect.Descriptor instead.
func (*RiwayatGolonganPesertaResponse) Descriptor() ([]byte, []int) {
	return file_riwayatgolonganpesertabkn_service_proto_rawDescGZIP(), []int{1}
}

func (x *RiwayatGolonganPesertaResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *RiwayatGolonganPesertaResponse) GetMessageCode() string {
	if x != nil {
		return x.MessageCode
	}
	return ""
}

func (x *RiwayatGolonganPesertaResponse) GetMessageDescription() string {
	if x != nil {
		return x.MessageDescription
	}
	return ""
}

func (x *RiwayatGolonganPesertaResponse) GetData() []*RiwayatGolonganPesertaData {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_riwayatgolonganpesertabkn_service_proto protoreflect.FileDescriptor

var file_riwayatgolonganpesertabkn_service_proto_rawDesc = []byte{
	0x0a, 0x27, 0x72, 0x69, 0x77, 0x61, 0x79, 0x61, 0x74, 0x67, 0x6f, 0x6c, 0x6f, 0x6e, 0x67, 0x61,
	0x6e, 0x70, 0x65, 0x73, 0x65, 0x72, 0x74, 0x61, 0x62, 0x6b, 0x6e, 0x5f, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x19, 0x72, 0x69, 0x77, 0x61, 0x79,
	0x61, 0x74, 0x67, 0x6f, 0x6c, 0x6f, 0x6e, 0x67, 0x61, 0x6e, 0x70, 0x65, 0x73, 0x65, 0x72, 0x74,
	0x61, 0x62, 0x6b, 0x6e, 0x1a, 0x27, 0x72, 0x69, 0x77, 0x61, 0x79, 0x61, 0x74, 0x67, 0x6f, 0x6c,
	0x6f, 0x6e, 0x67, 0x61, 0x6e, 0x70, 0x65, 0x73, 0x65, 0x72, 0x74, 0x61, 0x62, 0x6b, 0x6e, 0x5f,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x31, 0x0a,
	0x1d, 0x52, 0x69, 0x77, 0x61, 0x79, 0x61, 0x74, 0x47, 0x6f, 0x6c, 0x6f, 0x6e, 0x67, 0x61, 0x6e,
	0x50, 0x65, 0x73, 0x65, 0x72, 0x74, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10,
	0x0a, 0x03, 0x6e, 0x69, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6e, 0x69, 0x70,
	0x22, 0xd7, 0x01, 0x0a, 0x1e, 0x52, 0x69, 0x77, 0x61, 0x79, 0x61, 0x74, 0x47, 0x6f, 0x6c, 0x6f,
	0x6e, 0x67, 0x61, 0x6e, 0x50, 0x65, 0x73, 0x65, 0x72, 0x74, 0x61, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x21, 0x0a, 0x0c, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0b, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x2f,
	0x0a, 0x13, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x5f, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x12, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12,
	0x49, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x35, 0x2e,
	0x72, 0x69, 0x77, 0x61, 0x79, 0x61, 0x74, 0x67, 0x6f, 0x6c, 0x6f, 0x6e, 0x67, 0x61, 0x6e, 0x70,
	0x65, 0x73, 0x65, 0x72, 0x74, 0x61, 0x62, 0x6b, 0x6e, 0x2e, 0x52, 0x69, 0x77, 0x61, 0x79, 0x61,
	0x74, 0x47, 0x6f, 0x6c, 0x6f, 0x6e, 0x67, 0x61, 0x6e, 0x50, 0x65, 0x73, 0x65, 0x72, 0x74, 0x61,
	0x44, 0x61, 0x74, 0x61, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x32, 0xb0, 0x01, 0x0a, 0x19, 0x52,
	0x69, 0x77, 0x61, 0x79, 0x61, 0x74, 0x47, 0x6f, 0x6c, 0x6f, 0x6e, 0x67, 0x61, 0x6e, 0x50, 0x65,
	0x73, 0x65, 0x72, 0x74, 0x61, 0x42, 0x6b, 0x6e, 0x12, 0x92, 0x01, 0x0a, 0x19, 0x47, 0x65, 0x74,
	0x52, 0x69, 0x77, 0x61, 0x79, 0x61, 0x74, 0x47, 0x6f, 0x6c, 0x6f, 0x6e, 0x67, 0x61, 0x6e, 0x50,
	0x65, 0x73, 0x65, 0x72, 0x74, 0x61, 0x12, 0x38, 0x2e, 0x72, 0x69, 0x77, 0x61, 0x79, 0x61, 0x74,
	0x67, 0x6f, 0x6c, 0x6f, 0x6e, 0x67, 0x61, 0x6e, 0x70, 0x65, 0x73, 0x65, 0x72, 0x74, 0x61, 0x62,
	0x6b, 0x6e, 0x2e, 0x52, 0x69, 0x77, 0x61, 0x79, 0x61, 0x74, 0x47, 0x6f, 0x6c, 0x6f, 0x6e, 0x67,
	0x61, 0x6e, 0x50, 0x65, 0x73, 0x65, 0x72, 0x74, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x39, 0x2e, 0x72, 0x69, 0x77, 0x61, 0x79, 0x61, 0x74, 0x67, 0x6f, 0x6c, 0x6f, 0x6e, 0x67,
	0x61, 0x6e, 0x70, 0x65, 0x73, 0x65, 0x72, 0x74, 0x61, 0x62, 0x6b, 0x6e, 0x2e, 0x52, 0x69, 0x77,
	0x61, 0x79, 0x61, 0x74, 0x47, 0x6f, 0x6c, 0x6f, 0x6e, 0x67, 0x61, 0x6e, 0x50, 0x65, 0x73, 0x65,
	0x72, 0x74, 0x61, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x04, 0x5a,
	0x02, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_riwayatgolonganpesertabkn_service_proto_rawDescOnce sync.Once
	file_riwayatgolonganpesertabkn_service_proto_rawDescData = file_riwayatgolonganpesertabkn_service_proto_rawDesc
)

func file_riwayatgolonganpesertabkn_service_proto_rawDescGZIP() []byte {
	file_riwayatgolonganpesertabkn_service_proto_rawDescOnce.Do(func() {
		file_riwayatgolonganpesertabkn_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_riwayatgolonganpesertabkn_service_proto_rawDescData)
	})
	return file_riwayatgolonganpesertabkn_service_proto_rawDescData
}

var file_riwayatgolonganpesertabkn_service_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_riwayatgolonganpesertabkn_service_proto_goTypes = []interface{}{
	(*RiwayatGolonganPesertaRequest)(nil),  // 0: riwayatgolonganpesertabkn.RiwayatGolonganPesertaRequest
	(*RiwayatGolonganPesertaResponse)(nil), // 1: riwayatgolonganpesertabkn.RiwayatGolonganPesertaResponse
	(*RiwayatGolonganPesertaData)(nil),     // 2: riwayatgolonganpesertabkn.RiwayatGolonganPesertaData
}
var file_riwayatgolonganpesertabkn_service_proto_depIdxs = []int32{
	2, // 0: riwayatgolonganpesertabkn.RiwayatGolonganPesertaResponse.data:type_name -> riwayatgolonganpesertabkn.RiwayatGolonganPesertaData
	0, // 1: riwayatgolonganpesertabkn.RiwayatGolonganPesertaBkn.GetRiwayatGolonganPeserta:input_type -> riwayatgolonganpesertabkn.RiwayatGolonganPesertaRequest
	1, // 2: riwayatgolonganpesertabkn.RiwayatGolonganPesertaBkn.GetRiwayatGolonganPeserta:output_type -> riwayatgolonganpesertabkn.RiwayatGolonganPesertaResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_riwayatgolonganpesertabkn_service_proto_init() }
func file_riwayatgolonganpesertabkn_service_proto_init() {
	if File_riwayatgolonganpesertabkn_service_proto != nil {
		return
	}
	file_riwayatgolonganpesertabkn_message_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_riwayatgolonganpesertabkn_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RiwayatGolonganPesertaRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_riwayatgolonganpesertabkn_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RiwayatGolonganPesertaResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_riwayatgolonganpesertabkn_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_riwayatgolonganpesertabkn_service_proto_goTypes,
		DependencyIndexes: file_riwayatgolonganpesertabkn_service_proto_depIdxs,
		MessageInfos:      file_riwayatgolonganpesertabkn_service_proto_msgTypes,
	}.Build()
	File_riwayatgolonganpesertabkn_service_proto = out.File
	file_riwayatgolonganpesertabkn_service_proto_rawDesc = nil
	file_riwayatgolonganpesertabkn_service_proto_goTypes = nil
	file_riwayatgolonganpesertabkn_service_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// RiwayatGolonganPesertaBknClient is the client API for RiwayatGolonganPesertaBkn service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type RiwayatGolonganPesertaBknClient interface {
	GetRiwayatGolonganPeserta(ctx context.Context, in *RiwayatGolonganPesertaRequest, opts ...grpc.CallOption) (*RiwayatGolonganPesertaResponse, error)
}

type riwayatGolonganPesertaBknClient struct {
	cc grpc.ClientConnInterface
}

func NewRiwayatGolonganPesertaBknClient(cc grpc.ClientConnInterface) RiwayatGolonganPesertaBknClient {
	return &riwayatGolonganPesertaBknClient{cc}
}

func (c *riwayatGolonganPesertaBknClient) GetRiwayatGolonganPeserta(ctx context.Context, in *RiwayatGolonganPesertaRequest, opts ...grpc.CallOption) (*RiwayatGolonganPesertaResponse, error) {
	out := new(RiwayatGolonganPesertaResponse)
	err := c.cc.Invoke(ctx, "/riwayatgolonganpesertabkn.RiwayatGolonganPesertaBkn/GetRiwayatGolonganPeserta", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RiwayatGolonganPesertaBknServer is the server API for RiwayatGolonganPesertaBkn service.
type RiwayatGolonganPesertaBknServer interface {
	GetRiwayatGolonganPeserta(context.Context, *RiwayatGolonganPesertaRequest) (*RiwayatGolonganPesertaResponse, error)
}

// UnimplementedRiwayatGolonganPesertaBknServer can be embedded to have forward compatible implementations.
type UnimplementedRiwayatGolonganPesertaBknServer struct {
}

func (*UnimplementedRiwayatGolonganPesertaBknServer) GetRiwayatGolonganPeserta(context.Context, *RiwayatGolonganPesertaRequest) (*RiwayatGolonganPesertaResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRiwayatGolonganPeserta not implemented")
}

func RegisterRiwayatGolonganPesertaBknServer(s *grpc.Server, srv RiwayatGolonganPesertaBknServer) {
	s.RegisterService(&_RiwayatGolonganPesertaBkn_serviceDesc, srv)
}

func _RiwayatGolonganPesertaBkn_GetRiwayatGolonganPeserta_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RiwayatGolonganPesertaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RiwayatGolonganPesertaBknServer).GetRiwayatGolonganPeserta(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/riwayatgolonganpesertabkn.RiwayatGolonganPesertaBkn/GetRiwayatGolonganPeserta",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RiwayatGolonganPesertaBknServer).GetRiwayatGolonganPeserta(ctx, req.(*RiwayatGolonganPesertaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _RiwayatGolonganPesertaBkn_serviceDesc = grpc.ServiceDesc{
	ServiceName: "riwayatgolonganpesertabkn.RiwayatGolonganPesertaBkn",
	HandlerType: (*RiwayatGolonganPesertaBknServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetRiwayatGolonganPeserta",
			Handler:    _RiwayatGolonganPesertaBkn_GetRiwayatGolonganPeserta_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "riwayatgolonganpesertabkn_service.proto",
}
