// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.12.3
// source: redemptionbri_message.proto

package v1

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type RedemptionData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	//NAV Date (Mandatory) : Transaction Date
	//Format : yyyymmdd
	//Example : "20201231"
	NavDate string `protobuf:"bytes,1,opt,name=nav_date,json=navDate,proto3" json:"nav_date,omitempty"`
	//Reference No. (Mandatory)
	//Format : number(16)
	//Example : "1"
	ReferenceNo string `protobuf:"bytes,2,opt,name=reference_no,json=referenceNo,proto3" json:"reference_no,omitempty"`
	//SA Code (Mandatory) : BP Tapera Code
	//Format : char(5)
	//Example : "DBSI1"
	SaCode string `protobuf:"bytes,3,opt,name=sa_code,json=saCode,proto3" json:"sa_code,omitempty"`
	//Investor Fund Unit A/C No. (Mandatory)
	//Format : char(16) --> 5!c6!c3!c2!n
	//Example : "IFUAGBU001"
	InvestorFundUnitAcNo string `protobuf:"bytes,4,opt,name=investor_fund_unit_ac_no,json=investorFundUnitAcNo,proto3" json:"investor_fund_unit_ac_no,omitempty"`
	//Investor Fund Unit A/C Name (Mandatory)
	//Format : char(100)
	//Example : "IFUAGBU001 NAME"
	InvestorFundUnitAcName string `protobuf:"bytes,5,opt,name=investor_fund_unit_ac_name,json=investorFundUnitAcName,proto3" json:"investor_fund_unit_ac_name,omitempty"`
	//Fund Code (Mandatory) : Product Code
	//Format : char(16) --> 5!c2!c1!c6!c2!n
	//Example : "KIDT"
	FundCode string `protobuf:"bytes,6,opt,name=fund_code,json=fundCode,proto3" json:"fund_code,omitempty"`
}

func (x *RedemptionData) Reset() {
	*x = RedemptionData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_redemptionbri_message_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RedemptionData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RedemptionData) ProtoMessage() {}

func (x *RedemptionData) ProtoReflect() protoreflect.Message {
	mi := &file_redemptionbri_message_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RedemptionData.ProtoReflect.Descriptor instead.
func (*RedemptionData) Descriptor() ([]byte, []int) {
	return file_redemptionbri_message_proto_rawDescGZIP(), []int{0}
}

func (x *RedemptionData) GetNavDate() string {
	if x != nil {
		return x.NavDate
	}
	return ""
}

func (x *RedemptionData) GetReferenceNo() string {
	if x != nil {
		return x.ReferenceNo
	}
	return ""
}

func (x *RedemptionData) GetSaCode() string {
	if x != nil {
		return x.SaCode
	}
	return ""
}

func (x *RedemptionData) GetInvestorFundUnitAcNo() string {
	if x != nil {
		return x.InvestorFundUnitAcNo
	}
	return ""
}

func (x *RedemptionData) GetInvestorFundUnitAcName() string {
	if x != nil {
		return x.InvestorFundUnitAcName
	}
	return ""
}

func (x *RedemptionData) GetFundCode() string {
	if x != nil {
		return x.FundCode
	}
	return ""
}

type Data struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	//Reference No. (Mandatory)
	//Format : number(16)
	//Example : "1"
	ReferenceNo string `protobuf:"bytes,1,opt,name=reference_no,json=referenceNo,proto3" json:"reference_no,omitempty"`
}

func (x *Data) Reset() {
	*x = Data{}
	if protoimpl.UnsafeEnabled {
		mi := &file_redemptionbri_message_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Data) ProtoMessage() {}

func (x *Data) ProtoReflect() protoreflect.Message {
	mi := &file_redemptionbri_message_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Data.ProtoReflect.Descriptor instead.
func (*Data) Descriptor() ([]byte, []int) {
	return file_redemptionbri_message_proto_rawDescGZIP(), []int{1}
}

func (x *Data) GetReferenceNo() string {
	if x != nil {
		return x.ReferenceNo
	}
	return ""
}

var File_redemptionbri_message_proto protoreflect.FileDescriptor

var file_redemptionbri_message_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x72, 0x65, 0x64, 0x65, 0x6d, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x62, 0x72, 0x69, 0x5f,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0d, 0x72,
	0x65, 0x64, 0x65, 0x6d, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x62, 0x72, 0x69, 0x22, 0xf8, 0x01, 0x0a,
	0x0e, 0x52, 0x65, 0x64, 0x65, 0x6d, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x44, 0x61, 0x74, 0x61, 0x12,
	0x19, 0x0a, 0x08, 0x6e, 0x61, 0x76, 0x5f, 0x64, 0x61, 0x74, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x6e, 0x61, 0x76, 0x44, 0x61, 0x74, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x72, 0x65,
	0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x5f, 0x6e, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0b, 0x72, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x4e, 0x6f, 0x12, 0x17, 0x0a,
	0x07, 0x73, 0x61, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x73, 0x61, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x36, 0x0a, 0x18, 0x69, 0x6e, 0x76, 0x65, 0x73, 0x74,
	0x6f, 0x72, 0x5f, 0x66, 0x75, 0x6e, 0x64, 0x5f, 0x75, 0x6e, 0x69, 0x74, 0x5f, 0x61, 0x63, 0x5f,
	0x6e, 0x6f, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x14, 0x69, 0x6e, 0x76, 0x65, 0x73, 0x74,
	0x6f, 0x72, 0x46, 0x75, 0x6e, 0x64, 0x55, 0x6e, 0x69, 0x74, 0x41, 0x63, 0x4e, 0x6f, 0x12, 0x3a,
	0x0a, 0x1a, 0x69, 0x6e, 0x76, 0x65, 0x73, 0x74, 0x6f, 0x72, 0x5f, 0x66, 0x75, 0x6e, 0x64, 0x5f,
	0x75, 0x6e, 0x69, 0x74, 0x5f, 0x61, 0x63, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x16, 0x69, 0x6e, 0x76, 0x65, 0x73, 0x74, 0x6f, 0x72, 0x46, 0x75, 0x6e, 0x64,
	0x55, 0x6e, 0x69, 0x74, 0x41, 0x63, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x66, 0x75,
	0x6e, 0x64, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x66,
	0x75, 0x6e, 0x64, 0x43, 0x6f, 0x64, 0x65, 0x22, 0x29, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x61, 0x12,
	0x21, 0x0a, 0x0c, 0x72, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x5f, 0x6e, 0x6f, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x72, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65,
	0x4e, 0x6f, 0x42, 0x1a, 0x5a, 0x0c, 0x72, 0x65, 0x64, 0x65, 0x65, 0x6d, 0x62, 0x72, 0x69, 0x2f,
	0x76, 0x31, 0xa2, 0x02, 0x09, 0x72, 0x65, 0x64, 0x65, 0x65, 0x6d, 0x62, 0x72, 0x69, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_redemptionbri_message_proto_rawDescOnce sync.Once
	file_redemptionbri_message_proto_rawDescData = file_redemptionbri_message_proto_rawDesc
)

func file_redemptionbri_message_proto_rawDescGZIP() []byte {
	file_redemptionbri_message_proto_rawDescOnce.Do(func() {
		file_redemptionbri_message_proto_rawDescData = protoimpl.X.CompressGZIP(file_redemptionbri_message_proto_rawDescData)
	})
	return file_redemptionbri_message_proto_rawDescData
}

var file_redemptionbri_message_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_redemptionbri_message_proto_goTypes = []interface{}{
	(*RedemptionData)(nil), // 0: redemptionbri.RedemptionData
	(*Data)(nil),           // 1: redemptionbri.Data
}
var file_redemptionbri_message_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_redemptionbri_message_proto_init() }
func file_redemptionbri_message_proto_init() {
	if File_redemptionbri_message_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_redemptionbri_message_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RedemptionData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_redemptionbri_message_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Data); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_redemptionbri_message_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_redemptionbri_message_proto_goTypes,
		DependencyIndexes: file_redemptionbri_message_proto_depIdxs,
		MessageInfos:      file_redemptionbri_message_proto_msgTypes,
	}.Build()
	File_redemptionbri_message_proto = out.File
	file_redemptionbri_message_proto_rawDesc = nil
	file_redemptionbri_message_proto_goTypes = nil
	file_redemptionbri_message_proto_depIdxs = nil
}
