// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.12.3
// source: cancelredemptionbri.proto

package v1

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

//Request message for service Cancel Redemption
type CancelRedemptionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	//Reference No.(Mandatory)
	//Format : char(20)
	//Example : "7"
	ReferenceNo string `protobuf:"bytes,1,opt,name=reference_no,json=referenceNo,proto3" json:"reference_no,omitempty"`
}

func (x *CancelRedemptionRequest) Reset() {
	*x = CancelRedemptionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cancelredemptionbri_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CancelRedemptionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelRedemptionRequest) ProtoMessage() {}

func (x *CancelRedemptionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cancelredemptionbri_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelRedemptionRequest.ProtoReflect.Descriptor instead.
func (*CancelRedemptionRequest) Descriptor() ([]byte, []int) {
	return file_cancelredemptionbri_proto_rawDescGZIP(), []int{0}
}

func (x *CancelRedemptionRequest) GetReferenceNo() string {
	if x != nil {
		return x.ReferenceNo
	}
	return ""
}

//Response message for service Cancel Redemption
type CancelRedemptionResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	//Status from API Cancel Redemption BRI per reference no
	//Format : Success/Failed/Error
	//Success : response from BRI --> http 200 and status true
	//Failed : response from BRI --> http 200 and status false
	//Error : response from BRI --> other than http 200
	Status string `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	//Response Code from API Cancel Redemption BRI per reference no
	MessageCode string `protobuf:"bytes,2,opt,name=message_code,json=messageCode,proto3" json:"message_code,omitempty"`
	//Response Description from API Cancel Redemption BRI per reference no
	MessageDescription string `protobuf:"bytes,3,opt,name=message_description,json=messageDescription,proto3" json:"message_description,omitempty"`
	//Data per reference no
	Data *Data `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *CancelRedemptionResponse) Reset() {
	*x = CancelRedemptionResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cancelredemptionbri_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CancelRedemptionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelRedemptionResponse) ProtoMessage() {}

func (x *CancelRedemptionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cancelredemptionbri_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelRedemptionResponse.ProtoReflect.Descriptor instead.
func (*CancelRedemptionResponse) Descriptor() ([]byte, []int) {
	return file_cancelredemptionbri_proto_rawDescGZIP(), []int{1}
}

func (x *CancelRedemptionResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *CancelRedemptionResponse) GetMessageCode() string {
	if x != nil {
		return x.MessageCode
	}
	return ""
}

func (x *CancelRedemptionResponse) GetMessageDescription() string {
	if x != nil {
		return x.MessageDescription
	}
	return ""
}

func (x *CancelRedemptionResponse) GetData() *Data {
	if x != nil {
		return x.Data
	}
	return nil
}

type Data struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	//Reference No.(Mandatory)
	//Format : char(20)
	//Example : "7"
	ReferenceNo string `protobuf:"bytes,1,opt,name=reference_no,json=referenceNo,proto3" json:"reference_no,omitempty"`
}

func (x *Data) Reset() {
	*x = Data{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cancelredemptionbri_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Data) ProtoMessage() {}

func (x *Data) ProtoReflect() protoreflect.Message {
	mi := &file_cancelredemptionbri_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Data.ProtoReflect.Descriptor instead.
func (*Data) Descriptor() ([]byte, []int) {
	return file_cancelredemptionbri_proto_rawDescGZIP(), []int{2}
}

func (x *Data) GetReferenceNo() string {
	if x != nil {
		return x.ReferenceNo
	}
	return ""
}

var File_cancelredemptionbri_proto protoreflect.FileDescriptor

var file_cancelredemptionbri_proto_rawDesc = []byte{
	0x0a, 0x19, 0x63, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x72, 0x65, 0x64, 0x65, 0x6d, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x62, 0x72, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x13, 0x63, 0x61, 0x6e,
	0x63, 0x65, 0x6c, 0x72, 0x65, 0x64, 0x65, 0x6d, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x62, 0x72, 0x69,
	0x22, 0x3c, 0x0a, 0x17, 0x43, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x52, 0x65, 0x64, 0x65, 0x6d, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x21, 0x0a, 0x0c, 0x72,
	0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x5f, 0x6e, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0b, 0x72, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x4e, 0x6f, 0x22, 0xb5,
	0x01, 0x0a, 0x18, 0x43, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x52, 0x65, 0x64, 0x65, 0x6d, 0x70, 0x74,
	0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x12, 0x21, 0x0a, 0x0c, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x5f, 0x63,
	0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x2f, 0x0a, 0x13, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x5f, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x12, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x44, 0x65, 0x73, 0x63,
	0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x2d, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x63, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x72, 0x65,
	0x64, 0x65, 0x6d, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x62, 0x72, 0x69, 0x2e, 0x44, 0x61, 0x74, 0x61,
	0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x29, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x61, 0x12, 0x21,
	0x0a, 0x0c, 0x72, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x5f, 0x6e, 0x6f, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x72, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x4e,
	0x6f, 0x32, 0x88, 0x01, 0x0a, 0x13, 0x43, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x52, 0x65, 0x64, 0x65,
	0x6d, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x42, 0x72, 0x69, 0x12, 0x71, 0x0a, 0x10, 0x43, 0x61, 0x6e,
	0x63, 0x65, 0x6c, 0x52, 0x65, 0x64, 0x65, 0x6d, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x2c, 0x2e,
	0x63, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x72, 0x65, 0x64, 0x65, 0x6d, 0x70, 0x74, 0x69, 0x6f, 0x6e,
	0x62, 0x72, 0x69, 0x2e, 0x43, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x52, 0x65, 0x64, 0x65, 0x6d, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2d, 0x2e, 0x63, 0x61,
	0x6e, 0x63, 0x65, 0x6c, 0x72, 0x65, 0x64, 0x65, 0x6d, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x62, 0x72,
	0x69, 0x2e, 0x43, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x52, 0x65, 0x64, 0x65, 0x6d, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x04, 0x5a, 0x02,
	0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_cancelredemptionbri_proto_rawDescOnce sync.Once
	file_cancelredemptionbri_proto_rawDescData = file_cancelredemptionbri_proto_rawDesc
)

func file_cancelredemptionbri_proto_rawDescGZIP() []byte {
	file_cancelredemptionbri_proto_rawDescOnce.Do(func() {
		file_cancelredemptionbri_proto_rawDescData = protoimpl.X.CompressGZIP(file_cancelredemptionbri_proto_rawDescData)
	})
	return file_cancelredemptionbri_proto_rawDescData
}

var file_cancelredemptionbri_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_cancelredemptionbri_proto_goTypes = []interface{}{
	(*CancelRedemptionRequest)(nil),  // 0: cancelredemptionbri.CancelRedemptionRequest
	(*CancelRedemptionResponse)(nil), // 1: cancelredemptionbri.CancelRedemptionResponse
	(*Data)(nil),                     // 2: cancelredemptionbri.Data
}
var file_cancelredemptionbri_proto_depIdxs = []int32{
	2, // 0: cancelredemptionbri.CancelRedemptionResponse.data:type_name -> cancelredemptionbri.Data
	0, // 1: cancelredemptionbri.CancelRedemptionBri.CancelRedemption:input_type -> cancelredemptionbri.CancelRedemptionRequest
	1, // 2: cancelredemptionbri.CancelRedemptionBri.CancelRedemption:output_type -> cancelredemptionbri.CancelRedemptionResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_cancelredemptionbri_proto_init() }
func file_cancelredemptionbri_proto_init() {
	if File_cancelredemptionbri_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_cancelredemptionbri_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CancelRedemptionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cancelredemptionbri_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CancelRedemptionResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cancelredemptionbri_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Data); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_cancelredemptionbri_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_cancelredemptionbri_proto_goTypes,
		DependencyIndexes: file_cancelredemptionbri_proto_depIdxs,
		MessageInfos:      file_cancelredemptionbri_proto_msgTypes,
	}.Build()
	File_cancelredemptionbri_proto = out.File
	file_cancelredemptionbri_proto_rawDesc = nil
	file_cancelredemptionbri_proto_goTypes = nil
	file_cancelredemptionbri_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// CancelRedemptionBriClient is the client API for CancelRedemptionBri service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CancelRedemptionBriClient interface {
	CancelRedemption(ctx context.Context, in *CancelRedemptionRequest, opts ...grpc.CallOption) (*CancelRedemptionResponse, error)
}

type cancelRedemptionBriClient struct {
	cc grpc.ClientConnInterface
}

func NewCancelRedemptionBriClient(cc grpc.ClientConnInterface) CancelRedemptionBriClient {
	return &cancelRedemptionBriClient{cc}
}

func (c *cancelRedemptionBriClient) CancelRedemption(ctx context.Context, in *CancelRedemptionRequest, opts ...grpc.CallOption) (*CancelRedemptionResponse, error) {
	out := new(CancelRedemptionResponse)
	err := c.cc.Invoke(ctx, "/cancelredemptionbri.CancelRedemptionBri/CancelRedemption", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CancelRedemptionBriServer is the server API for CancelRedemptionBri service.
type CancelRedemptionBriServer interface {
	CancelRedemption(context.Context, *CancelRedemptionRequest) (*CancelRedemptionResponse, error)
}

// UnimplementedCancelRedemptionBriServer can be embedded to have forward compatible implementations.
type UnimplementedCancelRedemptionBriServer struct {
}

func (*UnimplementedCancelRedemptionBriServer) CancelRedemption(context.Context, *CancelRedemptionRequest) (*CancelRedemptionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CancelRedemption not implemented")
}

func RegisterCancelRedemptionBriServer(s *grpc.Server, srv CancelRedemptionBriServer) {
	s.RegisterService(&_CancelRedemptionBri_serviceDesc, srv)
}

func _CancelRedemptionBri_CancelRedemption_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelRedemptionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CancelRedemptionBriServer).CancelRedemption(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cancelredemptionbri.CancelRedemptionBri/CancelRedemption",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CancelRedemptionBriServer).CancelRedemption(ctx, req.(*CancelRedemptionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _CancelRedemptionBri_serviceDesc = grpc.ServiceDesc{
	ServiceName: "cancelredemptionbri.CancelRedemptionBri",
	HandlerType: (*CancelRedemptionBriServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CancelRedemption",
			Handler:    _CancelRedemptionBri_CancelRedemption_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "cancelredemptionbri.proto",
}
