// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.12.3
// source: pendaftaranpesertabri_service.proto

package v1

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type PendaftaranPesertaRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []*PendaftaranPesertaData `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
}

func (x *PendaftaranPesertaRequest) Reset() {
	*x = PendaftaranPesertaRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pendaftaranpesertabri_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PendaftaranPesertaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PendaftaranPesertaRequest) ProtoMessage() {}

func (x *PendaftaranPesertaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pendaftaranpesertabri_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PendaftaranPesertaRequest.ProtoReflect.Descriptor instead.
func (*PendaftaranPesertaRequest) Descriptor() ([]byte, []int) {
	return file_pendaftaranpesertabri_service_proto_rawDescGZIP(), []int{0}
}

func (x *PendaftaranPesertaRequest) GetData() []*PendaftaranPesertaData {
	if x != nil {
		return x.Data
	}
	return nil
}

type PendaftaranPesertaResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status             string `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	MessageCode        string `protobuf:"bytes,2,opt,name=message_code,json=messageCode,proto3" json:"message_code,omitempty"`
	MessageDescription string `protobuf:"bytes,3,opt,name=message_description,json=messageDescription,proto3" json:"message_description,omitempty"`
	Data               *Data  `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *PendaftaranPesertaResponse) Reset() {
	*x = PendaftaranPesertaResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pendaftaranpesertabri_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PendaftaranPesertaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PendaftaranPesertaResponse) ProtoMessage() {}

func (x *PendaftaranPesertaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pendaftaranpesertabri_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PendaftaranPesertaResponse.ProtoReflect.Descriptor instead.
func (*PendaftaranPesertaResponse) Descriptor() ([]byte, []int) {
	return file_pendaftaranpesertabri_service_proto_rawDescGZIP(), []int{1}
}

func (x *PendaftaranPesertaResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *PendaftaranPesertaResponse) GetMessageCode() string {
	if x != nil {
		return x.MessageCode
	}
	return ""
}

func (x *PendaftaranPesertaResponse) GetMessageDescription() string {
	if x != nil {
		return x.MessageDescription
	}
	return ""
}

func (x *PendaftaranPesertaResponse) GetData() *Data {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_pendaftaranpesertabri_service_proto protoreflect.FileDescriptor

var file_pendaftaranpesertabri_service_proto_rawDesc = []byte{
	0x0a, 0x23, 0x70, 0x65, 0x6e, 0x64, 0x61, 0x66, 0x74, 0x61, 0x72, 0x61, 0x6e, 0x70, 0x65, 0x73,
	0x65, 0x72, 0x74, 0x61, 0x62, 0x72, 0x69, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x15, 0x70, 0x65, 0x6e, 0x64, 0x61, 0x66, 0x74, 0x61, 0x72,
	0x61, 0x6e, 0x70, 0x65, 0x73, 0x65, 0x72, 0x74, 0x61, 0x62, 0x72, 0x69, 0x1a, 0x23, 0x70, 0x65,
	0x6e, 0x64, 0x61, 0x66, 0x74, 0x61, 0x72, 0x61, 0x6e, 0x70, 0x65, 0x73, 0x65, 0x72, 0x74, 0x61,
	0x62, 0x72, 0x69, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x5e, 0x0a, 0x19, 0x50, 0x65, 0x6e, 0x64, 0x61, 0x66, 0x74, 0x61, 0x72, 0x61, 0x6e,
	0x50, 0x65, 0x73, 0x65, 0x72, 0x74, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x41,
	0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x2d, 0x2e, 0x70,
	0x65, 0x6e, 0x64, 0x61, 0x66, 0x74, 0x61, 0x72, 0x61, 0x6e, 0x70, 0x65, 0x73, 0x65, 0x72, 0x74,
	0x61, 0x62, 0x72, 0x69, 0x2e, 0x50, 0x65, 0x6e, 0x64, 0x61, 0x66, 0x74, 0x61, 0x72, 0x61, 0x6e,
	0x50, 0x65, 0x73, 0x65, 0x72, 0x74, 0x61, 0x44, 0x61, 0x74, 0x61, 0x52, 0x04, 0x64, 0x61, 0x74,
	0x61, 0x22, 0xb9, 0x01, 0x0a, 0x1a, 0x50, 0x65, 0x6e, 0x64, 0x61, 0x66, 0x74, 0x61, 0x72, 0x61,
	0x6e, 0x50, 0x65, 0x73, 0x65, 0x72, 0x74, 0x61, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x21, 0x0a, 0x0c, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x2f, 0x0a, 0x13, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x5f, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x12, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x2f, 0x0a, 0x04,
	0x64, 0x61, 0x74, 0x61, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x70, 0x65, 0x6e,
	0x64, 0x61, 0x66, 0x74, 0x61, 0x72, 0x61, 0x6e, 0x70, 0x65, 0x73, 0x65, 0x72, 0x74, 0x61, 0x62,
	0x72, 0x69, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x32, 0x96, 0x01,
	0x0a, 0x15, 0x50, 0x65, 0x6e, 0x64, 0x61, 0x66, 0x74, 0x61, 0x72, 0x61, 0x6e, 0x50, 0x65, 0x73,
	0x65, 0x72, 0x74, 0x61, 0x42, 0x72, 0x69, 0x12, 0x7d, 0x0a, 0x12, 0x50, 0x65, 0x6e, 0x64, 0x61,
	0x66, 0x74, 0x61, 0x72, 0x61, 0x6e, 0x50, 0x65, 0x73, 0x65, 0x72, 0x74, 0x61, 0x12, 0x30, 0x2e,
	0x70, 0x65, 0x6e, 0x64, 0x61, 0x66, 0x74, 0x61, 0x72, 0x61, 0x6e, 0x70, 0x65, 0x73, 0x65, 0x72,
	0x74, 0x61, 0x62, 0x72, 0x69, 0x2e, 0x50, 0x65, 0x6e, 0x64, 0x61, 0x66, 0x74, 0x61, 0x72, 0x61,
	0x6e, 0x50, 0x65, 0x73, 0x65, 0x72, 0x74, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x31, 0x2e, 0x70, 0x65, 0x6e, 0x64, 0x61, 0x66, 0x74, 0x61, 0x72, 0x61, 0x6e, 0x70, 0x65, 0x73,
	0x65, 0x72, 0x74, 0x61, 0x62, 0x72, 0x69, 0x2e, 0x50, 0x65, 0x6e, 0x64, 0x61, 0x66, 0x74, 0x61,
	0x72, 0x61, 0x6e, 0x50, 0x65, 0x73, 0x65, 0x72, 0x74, 0x61, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x00, 0x30, 0x01, 0x42, 0x04, 0x5a, 0x02, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pendaftaranpesertabri_service_proto_rawDescOnce sync.Once
	file_pendaftaranpesertabri_service_proto_rawDescData = file_pendaftaranpesertabri_service_proto_rawDesc
)

func file_pendaftaranpesertabri_service_proto_rawDescGZIP() []byte {
	file_pendaftaranpesertabri_service_proto_rawDescOnce.Do(func() {
		file_pendaftaranpesertabri_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_pendaftaranpesertabri_service_proto_rawDescData)
	})
	return file_pendaftaranpesertabri_service_proto_rawDescData
}

var file_pendaftaranpesertabri_service_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pendaftaranpesertabri_service_proto_goTypes = []interface{}{
	(*PendaftaranPesertaRequest)(nil),  // 0: pendaftaranpesertabri.PendaftaranPesertaRequest
	(*PendaftaranPesertaResponse)(nil), // 1: pendaftaranpesertabri.PendaftaranPesertaResponse
	(*PendaftaranPesertaData)(nil),     // 2: pendaftaranpesertabri.PendaftaranPesertaData
	(*Data)(nil),                       // 3: pendaftaranpesertabri.Data
}
var file_pendaftaranpesertabri_service_proto_depIdxs = []int32{
	2, // 0: pendaftaranpesertabri.PendaftaranPesertaRequest.data:type_name -> pendaftaranpesertabri.PendaftaranPesertaData
	3, // 1: pendaftaranpesertabri.PendaftaranPesertaResponse.data:type_name -> pendaftaranpesertabri.Data
	0, // 2: pendaftaranpesertabri.PendaftaranPesertaBri.PendaftaranPeserta:input_type -> pendaftaranpesertabri.PendaftaranPesertaRequest
	1, // 3: pendaftaranpesertabri.PendaftaranPesertaBri.PendaftaranPeserta:output_type -> pendaftaranpesertabri.PendaftaranPesertaResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_pendaftaranpesertabri_service_proto_init() }
func file_pendaftaranpesertabri_service_proto_init() {
	if File_pendaftaranpesertabri_service_proto != nil {
		return
	}
	file_pendaftaranpesertabri_message_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_pendaftaranpesertabri_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PendaftaranPesertaRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pendaftaranpesertabri_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PendaftaranPesertaResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pendaftaranpesertabri_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pendaftaranpesertabri_service_proto_goTypes,
		DependencyIndexes: file_pendaftaranpesertabri_service_proto_depIdxs,
		MessageInfos:      file_pendaftaranpesertabri_service_proto_msgTypes,
	}.Build()
	File_pendaftaranpesertabri_service_proto = out.File
	file_pendaftaranpesertabri_service_proto_rawDesc = nil
	file_pendaftaranpesertabri_service_proto_goTypes = nil
	file_pendaftaranpesertabri_service_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// PendaftaranPesertaBriClient is the client API for PendaftaranPesertaBri service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PendaftaranPesertaBriClient interface {
	PendaftaranPeserta(ctx context.Context, in *PendaftaranPesertaRequest, opts ...grpc.CallOption) (PendaftaranPesertaBri_PendaftaranPesertaClient, error)
}

type pendaftaranPesertaBriClient struct {
	cc grpc.ClientConnInterface
}

func NewPendaftaranPesertaBriClient(cc grpc.ClientConnInterface) PendaftaranPesertaBriClient {
	return &pendaftaranPesertaBriClient{cc}
}

func (c *pendaftaranPesertaBriClient) PendaftaranPeserta(ctx context.Context, in *PendaftaranPesertaRequest, opts ...grpc.CallOption) (PendaftaranPesertaBri_PendaftaranPesertaClient, error) {
	stream, err := c.cc.NewStream(ctx, &_PendaftaranPesertaBri_serviceDesc.Streams[0], "/pendaftaranpesertabri.PendaftaranPesertaBri/PendaftaranPeserta", opts...)
	if err != nil {
		return nil, err
	}
	x := &pendaftaranPesertaBriPendaftaranPesertaClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type PendaftaranPesertaBri_PendaftaranPesertaClient interface {
	Recv() (*PendaftaranPesertaResponse, error)
	grpc.ClientStream
}

type pendaftaranPesertaBriPendaftaranPesertaClient struct {
	grpc.ClientStream
}

func (x *pendaftaranPesertaBriPendaftaranPesertaClient) Recv() (*PendaftaranPesertaResponse, error) {
	m := new(PendaftaranPesertaResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// PendaftaranPesertaBriServer is the server API for PendaftaranPesertaBri service.
type PendaftaranPesertaBriServer interface {
	PendaftaranPeserta(*PendaftaranPesertaRequest, PendaftaranPesertaBri_PendaftaranPesertaServer) error
}

// UnimplementedPendaftaranPesertaBriServer can be embedded to have forward compatible implementations.
type UnimplementedPendaftaranPesertaBriServer struct {
}

func (*UnimplementedPendaftaranPesertaBriServer) PendaftaranPeserta(*PendaftaranPesertaRequest, PendaftaranPesertaBri_PendaftaranPesertaServer) error {
	return status.Errorf(codes.Unimplemented, "method PendaftaranPeserta not implemented")
}

func RegisterPendaftaranPesertaBriServer(s *grpc.Server, srv PendaftaranPesertaBriServer) {
	s.RegisterService(&_PendaftaranPesertaBri_serviceDesc, srv)
}

func _PendaftaranPesertaBri_PendaftaranPeserta_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(PendaftaranPesertaRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(PendaftaranPesertaBriServer).PendaftaranPeserta(m, &pendaftaranPesertaBriPendaftaranPesertaServer{stream})
}

type PendaftaranPesertaBri_PendaftaranPesertaServer interface {
	Send(*PendaftaranPesertaResponse) error
	grpc.ServerStream
}

type pendaftaranPesertaBriPendaftaranPesertaServer struct {
	grpc.ServerStream
}

func (x *pendaftaranPesertaBriPendaftaranPesertaServer) Send(m *PendaftaranPesertaResponse) error {
	return x.ServerStream.SendMsg(m)
}

var _PendaftaranPesertaBri_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pendaftaranpesertabri.PendaftaranPesertaBri",
	HandlerType: (*PendaftaranPesertaBriServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "PendaftaranPeserta",
			Handler:       _PendaftaranPesertaBri_PendaftaranPeserta_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "pendaftaranpesertabri_service.proto",
}
