// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.12.3
// source: subscriptionbri_service.proto

package v1

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type SubscribResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status              string `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	ResponseCode        string `protobuf:"bytes,2,opt,name=response_code,json=responseCode,proto3" json:"response_code,omitempty"`
	ResponseDescription string `protobuf:"bytes,3,opt,name=response_description,json=responseDescription,proto3" json:"response_description,omitempty"`
}

func (x *SubscribResponse) Reset() {
	*x = SubscribResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_subscriptionbri_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SubscribResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribResponse) ProtoMessage() {}

func (x *SubscribResponse) ProtoReflect() protoreflect.Message {
	mi := &file_subscriptionbri_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribResponse.ProtoReflect.Descriptor instead.
func (*SubscribResponse) Descriptor() ([]byte, []int) {
	return file_subscriptionbri_service_proto_rawDescGZIP(), []int{0}
}

func (x *SubscribResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *SubscribResponse) GetResponseCode() string {
	if x != nil {
		return x.ResponseCode
	}
	return ""
}

func (x *SubscribResponse) GetResponseDescription() string {
	if x != nil {
		return x.ResponseDescription
	}
	return ""
}

type SubscribRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Parm *SubscribData `protobuf:"bytes,1,opt,name=parm,proto3" json:"parm,omitempty"`
}

func (x *SubscribRequest) Reset() {
	*x = SubscribRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_subscriptionbri_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SubscribRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribRequest) ProtoMessage() {}

func (x *SubscribRequest) ProtoReflect() protoreflect.Message {
	mi := &file_subscriptionbri_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribRequest.ProtoReflect.Descriptor instead.
func (*SubscribRequest) Descriptor() ([]byte, []int) {
	return file_subscriptionbri_service_proto_rawDescGZIP(), []int{1}
}

func (x *SubscribRequest) GetParm() *SubscribData {
	if x != nil {
		return x.Parm
	}
	return nil
}

var File_subscriptionbri_service_proto protoreflect.FileDescriptor

var file_subscriptionbri_service_proto_rawDesc = []byte{
	0x0a, 0x1d, 0x73, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x62, 0x72,
	0x69, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x0f, 0x73, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x62, 0x72, 0x69,
	0x1a, 0x1d, 0x73, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x62, 0x72,
	0x69, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0x82, 0x01, 0x0a, 0x10, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x23, 0x0a, 0x0d,
	0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0c, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x43, 0x6f, 0x64,
	0x65, 0x12, 0x31, 0x0a, 0x14, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x5f, 0x64, 0x65,
	0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x13, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x22, 0x44, 0x0a, 0x0f, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x31, 0x0a, 0x04, 0x70, 0x61, 0x72, 0x6d, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x73, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x62, 0x72, 0x69, 0x2e, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62,
	0x44, 0x61, 0x74, 0x61, 0x52, 0x04, 0x70, 0x61, 0x72, 0x6d, 0x32, 0x68, 0x0a, 0x0f, 0x53, 0x75,
	0x62, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x42, 0x72, 0x69, 0x12, 0x55, 0x0a,
	0x0c, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x20, 0x2e,
	0x73, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x62, 0x72, 0x69, 0x2e,
	0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x21, 0x2e, 0x73, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x62, 0x72,
	0x69, 0x2e, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x00, 0x42, 0x04, 0x5a, 0x02, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_subscriptionbri_service_proto_rawDescOnce sync.Once
	file_subscriptionbri_service_proto_rawDescData = file_subscriptionbri_service_proto_rawDesc
)

func file_subscriptionbri_service_proto_rawDescGZIP() []byte {
	file_subscriptionbri_service_proto_rawDescOnce.Do(func() {
		file_subscriptionbri_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_subscriptionbri_service_proto_rawDescData)
	})
	return file_subscriptionbri_service_proto_rawDescData
}

var file_subscriptionbri_service_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_subscriptionbri_service_proto_goTypes = []interface{}{
	(*SubscribResponse)(nil), // 0: subscriptionbri.SubscribResponse
	(*SubscribRequest)(nil),  // 1: subscriptionbri.SubscribRequest
	(*SubscribData)(nil),     // 2: subscriptionbri.SubscribData
}
var file_subscriptionbri_service_proto_depIdxs = []int32{
	2, // 0: subscriptionbri.SubscribRequest.parm:type_name -> subscriptionbri.SubscribData
	1, // 1: subscriptionbri.SubscriptionBri.Subscription:input_type -> subscriptionbri.SubscribRequest
	0, // 2: subscriptionbri.SubscriptionBri.Subscription:output_type -> subscriptionbri.SubscribResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_subscriptionbri_service_proto_init() }
func file_subscriptionbri_service_proto_init() {
	if File_subscriptionbri_service_proto != nil {
		return
	}
	file_subscriptionbri_message_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_subscriptionbri_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SubscribResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_subscriptionbri_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SubscribRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_subscriptionbri_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_subscriptionbri_service_proto_goTypes,
		DependencyIndexes: file_subscriptionbri_service_proto_depIdxs,
		MessageInfos:      file_subscriptionbri_service_proto_msgTypes,
	}.Build()
	File_subscriptionbri_service_proto = out.File
	file_subscriptionbri_service_proto_rawDesc = nil
	file_subscriptionbri_service_proto_goTypes = nil
	file_subscriptionbri_service_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// SubscriptionBriClient is the client API for SubscriptionBri service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SubscriptionBriClient interface {
	Subscription(ctx context.Context, in *SubscribRequest, opts ...grpc.CallOption) (*SubscribResponse, error)
}

type subscriptionBriClient struct {
	cc grpc.ClientConnInterface
}

func NewSubscriptionBriClient(cc grpc.ClientConnInterface) SubscriptionBriClient {
	return &subscriptionBriClient{cc}
}

func (c *subscriptionBriClient) Subscription(ctx context.Context, in *SubscribRequest, opts ...grpc.CallOption) (*SubscribResponse, error) {
	out := new(SubscribResponse)
	err := c.cc.Invoke(ctx, "/subscriptionbri.SubscriptionBri/Subscription", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SubscriptionBriServer is the server API for SubscriptionBri service.
type SubscriptionBriServer interface {
	Subscription(context.Context, *SubscribRequest) (*SubscribResponse, error)
}

// UnimplementedSubscriptionBriServer can be embedded to have forward compatible implementations.
type UnimplementedSubscriptionBriServer struct {
}

func (*UnimplementedSubscriptionBriServer) Subscription(context.Context, *SubscribRequest) (*SubscribResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Subscription not implemented")
}

func RegisterSubscriptionBriServer(s *grpc.Server, srv SubscriptionBriServer) {
	s.RegisterService(&_SubscriptionBri_serviceDesc, srv)
}

func _SubscriptionBri_Subscription_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubscribRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubscriptionBriServer).Subscription(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/subscriptionbri.SubscriptionBri/Subscription",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubscriptionBriServer).Subscription(ctx, req.(*SubscribRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _SubscriptionBri_serviceDesc = grpc.ServiceDesc{
	ServiceName: "subscriptionbri.SubscriptionBri",
	HandlerType: (*SubscriptionBriServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Subscription",
			Handler:    _SubscriptionBri_Subscription_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "subscriptionbri_service.proto",
}
