// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.12.3
// source: adviceredemptionconfirmationbri.proto

package v1

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Status int32

const (
	Status_UNKNOWN_STATUS Status = 0
	Status_OPEN           Status = 1
	Status_REJECT         Status = 2
	Status_APPROVE        Status = 3
	Status_VALID          Status = 4
	Status_CANCEL         Status = 5
	Status_POSTED         Status = 6
)

// Enum value maps for Status.
var (
	Status_name = map[int32]string{
		0: "UNKNOWN_STATUS",
		1: "OPEN",
		2: "REJECT",
		3: "APPROVE",
		4: "VALID",
		5: "CANCEL",
		6: "POSTED",
	}
	Status_value = map[string]int32{
		"UNKNOWN_STATUS": 0,
		"OPEN":           1,
		"REJECT":         2,
		"APPROVE":        3,
		"VALID":          4,
		"CANCEL":         5,
		"POSTED":         6,
	}
)

func (x Status) Enum() *Status {
	p := new(Status)
	*p = x
	return p
}

func (x Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Status) Descriptor() protoreflect.EnumDescriptor {
	return file_adviceredemptionconfirmationbri_proto_enumTypes[0].Descriptor()
}

func (Status) Type() protoreflect.EnumType {
	return &file_adviceredemptionconfirmationbri_proto_enumTypes[0]
}

func (x Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Status.Descriptor instead.
func (Status) EnumDescriptor() ([]byte, []int) {
	return file_adviceredemptionconfirmationbri_proto_rawDescGZIP(), []int{0}
}

//Request message for service AdviceConfirm Redemption
type AdviceRedemptionConfirmationRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	//Reference No.(Mandatory)
	//Format : char(20)
	//Example : "7"
	ReferenceNo string `protobuf:"bytes,1,opt,name=reference_no,json=referenceNo,proto3" json:"reference_no,omitempty"`
}

func (x *AdviceRedemptionConfirmationRequest) Reset() {
	*x = AdviceRedemptionConfirmationRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_adviceredemptionconfirmationbri_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AdviceRedemptionConfirmationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdviceRedemptionConfirmationRequest) ProtoMessage() {}

func (x *AdviceRedemptionConfirmationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_adviceredemptionconfirmationbri_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdviceRedemptionConfirmationRequest.ProtoReflect.Descriptor instead.
func (*AdviceRedemptionConfirmationRequest) Descriptor() ([]byte, []int) {
	return file_adviceredemptionconfirmationbri_proto_rawDescGZIP(), []int{0}
}

func (x *AdviceRedemptionConfirmationRequest) GetReferenceNo() string {
	if x != nil {
		return x.ReferenceNo
	}
	return ""
}

//Response message for service Advice Confirm Redemption
type AdviceRedemptionConfirmationResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	//Status from API Advice Confirm Redemption BRI per reference no
	//Format : Success/Failed/Error
	//Success : response from BRI --> http 200 and status true
	//Failed : response from BRI --> http 200 and status false
	//Error : response from BRI --> other than http 200
	Status string `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	//Response Code from API Advice Confirm Redemption BRI per reference no
	MessageCode string `protobuf:"bytes,2,opt,name=message_code,json=messageCode,proto3" json:"message_code,omitempty"`
	//Response Description from API Advice Confirm Redemption BRI per reference no
	MessageDescription string `protobuf:"bytes,3,opt,name=message_description,json=messageDescription,proto3" json:"message_description,omitempty"`
	//Data per reference no
	Data *Data `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *AdviceRedemptionConfirmationResponse) Reset() {
	*x = AdviceRedemptionConfirmationResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_adviceredemptionconfirmationbri_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AdviceRedemptionConfirmationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdviceRedemptionConfirmationResponse) ProtoMessage() {}

func (x *AdviceRedemptionConfirmationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_adviceredemptionconfirmationbri_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdviceRedemptionConfirmationResponse.ProtoReflect.Descriptor instead.
func (*AdviceRedemptionConfirmationResponse) Descriptor() ([]byte, []int) {
	return file_adviceredemptionconfirmationbri_proto_rawDescGZIP(), []int{1}
}

func (x *AdviceRedemptionConfirmationResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *AdviceRedemptionConfirmationResponse) GetMessageCode() string {
	if x != nil {
		return x.MessageCode
	}
	return ""
}

func (x *AdviceRedemptionConfirmationResponse) GetMessageDescription() string {
	if x != nil {
		return x.MessageDescription
	}
	return ""
}

func (x *AdviceRedemptionConfirmationResponse) GetData() *Data {
	if x != nil {
		return x.Data
	}
	return nil
}

type Data struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	//Reference No.
	//Format : char(20)
	//Example : "7"
	ReferenceNo string `protobuf:"bytes,1,opt,name=reference_no,json=referenceNo,proto3" json:"reference_no,omitempty"`
	//NAV Date : Transaction Date
	//Format : yyyymmdd
	//Example : "20201231"
	NavDate string `protobuf:"bytes,2,opt,name=nav_date,json=navDate,proto3" json:"nav_date,omitempty"`
	//Status redemption per reference no
	Status Status `protobuf:"varint,3,opt,name=status,proto3,enum=AdviceRedemptionConfirmationbri.Status" json:"status,omitempty"`
}

func (x *Data) Reset() {
	*x = Data{}
	if protoimpl.UnsafeEnabled {
		mi := &file_adviceredemptionconfirmationbri_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Data) ProtoMessage() {}

func (x *Data) ProtoReflect() protoreflect.Message {
	mi := &file_adviceredemptionconfirmationbri_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Data.ProtoReflect.Descriptor instead.
func (*Data) Descriptor() ([]byte, []int) {
	return file_adviceredemptionconfirmationbri_proto_rawDescGZIP(), []int{2}
}

func (x *Data) GetReferenceNo() string {
	if x != nil {
		return x.ReferenceNo
	}
	return ""
}

func (x *Data) GetNavDate() string {
	if x != nil {
		return x.NavDate
	}
	return ""
}

func (x *Data) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_UNKNOWN_STATUS
}

var File_adviceredemptionconfirmationbri_proto protoreflect.FileDescriptor

var file_adviceredemptionconfirmationbri_proto_rawDesc = []byte{
	0x0a, 0x25, 0x61, 0x64, 0x76, 0x69, 0x63, 0x65, 0x72, 0x65, 0x64, 0x65, 0x6d, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x72, 0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x62, 0x72,
	0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x1f, 0x41, 0x64, 0x76, 0x69, 0x63, 0x65, 0x52,
	0x65, 0x64, 0x65, 0x6d, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x72, 0x6d,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x62, 0x72, 0x69, 0x22, 0x48, 0x0a, 0x23, 0x41, 0x64, 0x76, 0x69,
	0x63, 0x65, 0x52, 0x65, 0x64, 0x65, 0x6d, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x43, 0x6f, 0x6e, 0x66,
	0x69, 0x72, 0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x21, 0x0a, 0x0c, 0x72, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x5f, 0x6e, 0x6f, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x72, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65,
	0x4e, 0x6f, 0x22, 0xcd, 0x01, 0x0a, 0x24, 0x41, 0x64, 0x76, 0x69, 0x63, 0x65, 0x52, 0x65, 0x64,
	0x65, 0x6d, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x72, 0x6d, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x12, 0x21, 0x0a, 0x0c, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x5f, 0x63,
	0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x2f, 0x0a, 0x13, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x5f, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x12, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x44, 0x65, 0x73, 0x63,
	0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x39, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x25, 0x2e, 0x41, 0x64, 0x76, 0x69, 0x63, 0x65, 0x52, 0x65,
	0x64, 0x65, 0x6d, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x72, 0x6d, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x62, 0x72, 0x69, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x52, 0x04, 0x64, 0x61,
	0x74, 0x61, 0x22, 0x85, 0x01, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x61, 0x12, 0x21, 0x0a, 0x0c, 0x72,
	0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x5f, 0x6e, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0b, 0x72, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x4e, 0x6f, 0x12, 0x19,
	0x0a, 0x08, 0x6e, 0x61, 0x76, 0x5f, 0x64, 0x61, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x6e, 0x61, 0x76, 0x44, 0x61, 0x74, 0x65, 0x12, 0x3f, 0x0a, 0x06, 0x73, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x27, 0x2e, 0x41, 0x64, 0x76, 0x69,
	0x63, 0x65, 0x52, 0x65, 0x64, 0x65, 0x6d, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x43, 0x6f, 0x6e, 0x66,
	0x69, 0x72, 0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x62, 0x72, 0x69, 0x2e, 0x53, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x2a, 0x62, 0x0a, 0x06, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x12, 0x12, 0x0a, 0x0e, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x5f,
	0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x10, 0x00, 0x12, 0x08, 0x0a, 0x04, 0x4f, 0x50, 0x45, 0x4e,
	0x10, 0x01, 0x12, 0x0a, 0x0a, 0x06, 0x52, 0x45, 0x4a, 0x45, 0x43, 0x54, 0x10, 0x02, 0x12, 0x0b,
	0x0a, 0x07, 0x41, 0x50, 0x50, 0x52, 0x4f, 0x56, 0x45, 0x10, 0x03, 0x12, 0x09, 0x0a, 0x05, 0x56,
	0x41, 0x4c, 0x49, 0x44, 0x10, 0x04, 0x12, 0x0a, 0x0a, 0x06, 0x43, 0x41, 0x4e, 0x43, 0x45, 0x4c,
	0x10, 0x05, 0x12, 0x0a, 0x0a, 0x06, 0x50, 0x4f, 0x53, 0x54, 0x45, 0x44, 0x10, 0x06, 0x32, 0xd1,
	0x01, 0x0a, 0x1f, 0x41, 0x64, 0x76, 0x69, 0x63, 0x65, 0x52, 0x65, 0x64, 0x65, 0x6d, 0x70, 0x74,
	0x69, 0x6f, 0x6e, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x72, 0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x42,
	0x72, 0x69, 0x12, 0xad, 0x01, 0x0a, 0x1c, 0x41, 0x64, 0x76, 0x69, 0x63, 0x65, 0x52, 0x65, 0x64,
	0x65, 0x6d, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x72, 0x6d, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x12, 0x44, 0x2e, 0x41, 0x64, 0x76, 0x69, 0x63, 0x65, 0x52, 0x65, 0x64, 0x65,
	0x6d, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x72, 0x6d, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x62, 0x72, 0x69, 0x2e, 0x41, 0x64, 0x76, 0x69, 0x63, 0x65, 0x52, 0x65, 0x64, 0x65,
	0x6d, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x72, 0x6d, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x45, 0x2e, 0x41, 0x64, 0x76, 0x69,
	0x63, 0x65, 0x52, 0x65, 0x64, 0x65, 0x6d, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x43, 0x6f, 0x6e, 0x66,
	0x69, 0x72, 0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x62, 0x72, 0x69, 0x2e, 0x41, 0x64, 0x76, 0x69,
	0x63, 0x65, 0x52, 0x65, 0x64, 0x65, 0x6d, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x43, 0x6f, 0x6e, 0x66,
	0x69, 0x72, 0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x00, 0x42, 0x04, 0x5a, 0x02, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_adviceredemptionconfirmationbri_proto_rawDescOnce sync.Once
	file_adviceredemptionconfirmationbri_proto_rawDescData = file_adviceredemptionconfirmationbri_proto_rawDesc
)

func file_adviceredemptionconfirmationbri_proto_rawDescGZIP() []byte {
	file_adviceredemptionconfirmationbri_proto_rawDescOnce.Do(func() {
		file_adviceredemptionconfirmationbri_proto_rawDescData = protoimpl.X.CompressGZIP(file_adviceredemptionconfirmationbri_proto_rawDescData)
	})
	return file_adviceredemptionconfirmationbri_proto_rawDescData
}

var file_adviceredemptionconfirmationbri_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_adviceredemptionconfirmationbri_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_adviceredemptionconfirmationbri_proto_goTypes = []interface{}{
	(Status)(0), // 0: AdviceRedemptionConfirmationbri.Status
	(*AdviceRedemptionConfirmationRequest)(nil),  // 1: AdviceRedemptionConfirmationbri.AdviceRedemptionConfirmationRequest
	(*AdviceRedemptionConfirmationResponse)(nil), // 2: AdviceRedemptionConfirmationbri.AdviceRedemptionConfirmationResponse
	(*Data)(nil), // 3: AdviceRedemptionConfirmationbri.Data
}
var file_adviceredemptionconfirmationbri_proto_depIdxs = []int32{
	3, // 0: AdviceRedemptionConfirmationbri.AdviceRedemptionConfirmationResponse.data:type_name -> AdviceRedemptionConfirmationbri.Data
	0, // 1: AdviceRedemptionConfirmationbri.Data.status:type_name -> AdviceRedemptionConfirmationbri.Status
	1, // 2: AdviceRedemptionConfirmationbri.AdviceRedemptionConfirmationBri.AdviceRedemptionConfirmation:input_type -> AdviceRedemptionConfirmationbri.AdviceRedemptionConfirmationRequest
	2, // 3: AdviceRedemptionConfirmationbri.AdviceRedemptionConfirmationBri.AdviceRedemptionConfirmation:output_type -> AdviceRedemptionConfirmationbri.AdviceRedemptionConfirmationResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_adviceredemptionconfirmationbri_proto_init() }
func file_adviceredemptionconfirmationbri_proto_init() {
	if File_adviceredemptionconfirmationbri_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_adviceredemptionconfirmationbri_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AdviceRedemptionConfirmationRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_adviceredemptionconfirmationbri_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AdviceRedemptionConfirmationResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_adviceredemptionconfirmationbri_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Data); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_adviceredemptionconfirmationbri_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_adviceredemptionconfirmationbri_proto_goTypes,
		DependencyIndexes: file_adviceredemptionconfirmationbri_proto_depIdxs,
		EnumInfos:         file_adviceredemptionconfirmationbri_proto_enumTypes,
		MessageInfos:      file_adviceredemptionconfirmationbri_proto_msgTypes,
	}.Build()
	File_adviceredemptionconfirmationbri_proto = out.File
	file_adviceredemptionconfirmationbri_proto_rawDesc = nil
	file_adviceredemptionconfirmationbri_proto_goTypes = nil
	file_adviceredemptionconfirmationbri_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// AdviceRedemptionConfirmationBriClient is the client API for AdviceRedemptionConfirmationBri service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AdviceRedemptionConfirmationBriClient interface {
	AdviceRedemptionConfirmation(ctx context.Context, in *AdviceRedemptionConfirmationRequest, opts ...grpc.CallOption) (*AdviceRedemptionConfirmationResponse, error)
}

type adviceRedemptionConfirmationBriClient struct {
	cc grpc.ClientConnInterface
}

func NewAdviceRedemptionConfirmationBriClient(cc grpc.ClientConnInterface) AdviceRedemptionConfirmationBriClient {
	return &adviceRedemptionConfirmationBriClient{cc}
}

func (c *adviceRedemptionConfirmationBriClient) AdviceRedemptionConfirmation(ctx context.Context, in *AdviceRedemptionConfirmationRequest, opts ...grpc.CallOption) (*AdviceRedemptionConfirmationResponse, error) {
	out := new(AdviceRedemptionConfirmationResponse)
	err := c.cc.Invoke(ctx, "/AdviceRedemptionConfirmationbri.AdviceRedemptionConfirmationBri/AdviceRedemptionConfirmation", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AdviceRedemptionConfirmationBriServer is the server API for AdviceRedemptionConfirmationBri service.
type AdviceRedemptionConfirmationBriServer interface {
	AdviceRedemptionConfirmation(context.Context, *AdviceRedemptionConfirmationRequest) (*AdviceRedemptionConfirmationResponse, error)
}

// UnimplementedAdviceRedemptionConfirmationBriServer can be embedded to have forward compatible implementations.
type UnimplementedAdviceRedemptionConfirmationBriServer struct {
}

func (*UnimplementedAdviceRedemptionConfirmationBriServer) AdviceRedemptionConfirmation(context.Context, *AdviceRedemptionConfirmationRequest) (*AdviceRedemptionConfirmationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AdviceRedemptionConfirmation not implemented")
}

func RegisterAdviceRedemptionConfirmationBriServer(s *grpc.Server, srv AdviceRedemptionConfirmationBriServer) {
	s.RegisterService(&_AdviceRedemptionConfirmationBri_serviceDesc, srv)
}

func _AdviceRedemptionConfirmationBri_AdviceRedemptionConfirmation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdviceRedemptionConfirmationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdviceRedemptionConfirmationBriServer).AdviceRedemptionConfirmation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/AdviceRedemptionConfirmationbri.AdviceRedemptionConfirmationBri/AdviceRedemptionConfirmation",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdviceRedemptionConfirmationBriServer).AdviceRedemptionConfirmation(ctx, req.(*AdviceRedemptionConfirmationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _AdviceRedemptionConfirmationBri_serviceDesc = grpc.ServiceDesc{
	ServiceName: "AdviceRedemptionConfirmationbri.AdviceRedemptionConfirmationBri",
	HandlerType: (*AdviceRedemptionConfirmationBriServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AdviceRedemptionConfirmation",
			Handler:    _AdviceRedemptionConfirmationBri_AdviceRedemptionConfirmation_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "adviceredemptionconfirmationbri.proto",
}
